### PR TITLE
Improved the email validator by making sure the domain name is valid.

### PR DESCRIPTION
**Pull request by jabarihunt**
The `validateEmail()` method now does the following:

1. Performs a `filter_var()` check with the `FILTER_VALIDATE_EMAIL` flag
2. Extracts a fully qualified ASCII domain name from the email address
3. **Checks to make sure that the domain has a DNS record**

This doesn't guarantee that the email account is valid (which is impossible), but it will check to make sure that the domain exists and has DNS entries.  It doesn't look for MX entries in particular because it's possible they may not be present for certain domains, though email is sent using them.

### CODE REVIEW

**Comment by willemwollebrants** [comment]
Thanks for your effort, but I won't be merging this in (unless you can change my mind :)). This has been suggested before, but there are serious downsides to consider (See my comment over at #159 ).

Long story short: it's a lot of overhead and the result still can't be trusted.  If you want to make sure a user provides a valid address, you're going to have to  send them an e-mail with a confirmation link at some point.

**Comment by jabarihunt** [comment]
Hmmm...what if I included a third parameter, something like:
`protected function validateEmail($field, $value, $checkDomain = false)`

...that way existing functionality would remain exactly the same, but if someone wanted to the the check they can set it to true.

**Comment by willemwollebrants** [comment]
Thanks. I'm looking at the code and there's a little problem: it introduces a dependency on the intl-extension (by using the idn_to_ascii function()). I'm trying to add some testing too and it turns out that running checkdnsrr() on a non-existing domain is really really slow. I'll do some more thinking :)

**Comment by jabarihunt** [comment]
Please keep in mind, the default behavior is that the DNS check will **_not_** happen unless it's explicitly called.  If someone pulled this updated method into an existing instance, absolutely nothing would change in their functionality.  Additionally, this is something that would only be explicitly called when a user is either signing up for the first time with an email address or changing their email address.

As far as running slow for non-existing domains...this applies to people who are trying to spam anyway (and maybe the occasional typo).  Yes, I understand that additional server resources would be tied up during a DDoS attack on a form page, but at that point there are other far more pressing concerns.

This code simply adds as additional option for developers to use if they so choose.

**Comment by vlucas** [comment]
We cannot merge this in as-is over the default existing `email` type. You should consider adding this as a separate type instead, like `emailDNS`, etc. As @willemwollebrants stated, there are simply too many downsides to this, and will negatively impact everyone who currently uses it immediately upon upgrading.

**Comment by jabarihunt** [comment]
Will do (though, the last commit should have zero impact on anyone who merged this since domain checking has to be explicitly called).

I'll create a separate validation method and commit it...

**Comment by jabarihunt** [comment]
I commited the changes.  Something to note...

The `idn_to_ascii()` method returns an FQDN compatible host name even if the domain has international charaters.  If a domain has international charaters `checkdnsrr()` may return false negatives and will probably be slow in doing so (http://php.net/manual/en/function.checkdnsrr.php#113537).  However, I removed it for a couple of reasons:

1) @willemwollebrants didn't like the dependency to the intl extension (which is understandable)
2) You guys aren't using it in the `validateUrlActive()` method (which uses `checkdnsrr()` as well)

BTW - the `validateUrlActive()` method isn't placing a dot (.) at the end of the domain name.  Again, `checkdnsrr()` likes FQDNs! (http://php.net/manual/en/function.checkdnsrr.php#119969)

**Comment by willemwollebrants** [comment]
I've been doing some thinking: using idn_to_ascii() is probably the right way to go if we want to support validating non-latin url's and e-mail addresses (see also #234 ) but we don't want to force it as a dependency. 

Perhaps the best solution would be to use idn_to_ascii() if it is available (`if(function_exists('idn_to_ascii'))`) and`suggest` ext-intl in the composer.json file.

**Comment by jabarihunt** [comment]
I took your suggestion one step further and added a check for the required constant (`INTL_IDNA_VARIANT_UTS46`) that `idn_to_ascii()` requires as well.  The new method:
```
protected function validateEmailDNS($field, $value)
{
    if ($this->validateEmail($field, $value)) {
        $domain = ltrim(stristr($value, '@'), '@') . '.';
        if (function_exists('idn_to_ascii') && defined('INTL_IDNA_VARIANT_UTS46')) {
            $domain = idn_to_ascii($domain, 0, INTL_IDNA_VARIANT_UTS46);
        }
        return checkdnsrr($domain, 'ANY');
    }

    return false;
}
```

**Comment by jabarihunt** [comment]
Any update on this?  Right now I'm simply extending Valitron and adding a custom rule that does the exact same thing.  I have a couple of other projects coming down the pipe that will use this validation as well.  It would be great if it were included in already (and I'm certain there are many others who'd use it as well). ;-)

**Comment by willemwollebrants** [comment]
I sent you a PR with some tests :)

**Comment by jabarihunt** [comment]
@willemwollebrants  Merged...thank you Sir!

**Pull request merged**
