### PR TITLE
Array contains and unique validators

### PR DESCRIPTION
**Pull request by misantron**

### CODE REVIEW

**Comment by misantron** [comment]
TravisCI failed build on php 5.3 cause of error:
The command "phpenv global 5.3" failed and exited with 1 during.
They seem to have problems with virtual env.

**Comment by misantron** [comment]
@willemwollebrants any comments?

**Comment by willemwollebrants** [comment]
Sorry, I've been sick and am now drowning in work :( I'll look at it this week

**Comment by misantron** [comment]
@willemwollebrants thx for the response. Get well.

**Comment by willemwollebrants** [comment]
Ok, I finally managed to look it over. First of all, thanks a lot, it's an impressive amount of code :) 

I think it would be a good idea to change the name 'unique' to, for example, 'containsUnique' or 'uniqueElements'. I think it would make sense that a 'unique' rule would check  if the given value is unique in the whole dataset (the one you pass in the constructor), not just one element of it. 

For 'arrayContains' I'm a bit conflicted too. Consider this:
```php
$v = new Validator(array('test_field' => array('black', 45)));
$v->rule('arrayContains', 'test_field', 'black');
```
This will return false, because 'black' is not an array. However, 'test_field' *is* an array that contains 'black'. I think it would be understandable if a user thinks this should return true. (It would act as an alias for the 'in'-rule).

One last thing: I see you've done a lot of cleaning up and some style changes. Let me be clear: that's awesome 👍 Just for the future: it's a lot easier for me (and I guess for a lot of other maintainers too) to have one thing per PR (One for the new rules, another one for the style fixes). Just a minor thing, but it makes reviewing a little bit easier.

**Comment by misantron** [comment]
@willemwollebrants thx for code review. I'll make fixes as soon as possible.

**Comment by misantron** [comment]
Apologize for all-in-one (new rules and code style fixes) PR. I understand that it's realy hard to review. Waiting for the feedback.

**Comment by willemwollebrants** [comment]
Thanks for your continued patience. 
I like the new name for the `containsUnique` rule 👍
I'm still not quite happy with the `arrayContains` rule and it seems I've been mistaken about what that rule does, because of the name.
Consider this example: 
```php
$a = ['a', 'b', 'c'];
$b = ['a', 'b', 'c', 'd', 'e', 'f'];
```
I would say that $b 'contains' $a, and that $a 'is contained within' $b. But it looks like the rule works the other way around. It checks if all values of $a are also present in $b. The order happens to match in my example, but that doesn't matter I think.
If I remember my patterns correctly, there are 3 terms for part of an array:

1. subarray : part of the original array in the same order, without skipping any element (`['b','c','d']`)
2. subsequence : part of the original array in the same order, but skipping elements is ok (`['b','d','f']`)
3. subset : we don't care about the order, we can skip whatever we want, but all elements must be in the original array ((`['f','a','b']`)

I think `subset` matches what you want to rule to do, so maybe we should name it just that. (sorry about all the theory 😬)

**Comment by misantron** [comment]
@willemwollebrants You're right `subset` is the best name for this rule.

**Pull request merged**
