### PR TITLE
Don't add {field} to message uf already exists

### PR DESCRIPTION
**Pull request by jatubio**
Fixed rule() function to don't add {field} to message if already exists on them

### CODE REVIEW

**Comment by willemwollebrants** [comment]
Good idea, but we can't be sure that mb_strpos() is available (take a look at how the other mb_* functions are used, [example](https://github.com/vlucas/valitron/blob/master/src/Valitron/Validator.php#L458)

If you could also add a test, that would be even more awesome :)

**Comment by jatubio** [comment]
Thank you for the example. I have modified my code :)

Sorry for the test, but I don't know how to write tests and I have not configured my development environment to run tests :(

**Comment by jatubio** [comment]
If someone wants to write a test:

The problem to solve is when `$_ruleMessages` have some messages containing `{field}` and rule() function add also `{field}` to message.

**Comment by willemwollebrants** [comment]
Thanks, can you provide me a piece of code that did not work before? I'm not entirely sure what's going on but I can't reproduce the problem 100% I'm afraid.

**Comment by jatubio** [comment]
Of course, I'm happy to help improve this great validation library!

```
<?php

use Valitron\Validator;

class ChildValidator extends Validator
{
    public function addCustomMessages()
    {
        static::$_ruleMessages['required']='You have to put something on {field}';
    }
}

$v=new ChildValidator(['name'=>NULL,'phone'=>'88811212']);
$v->addCustomMessages();
$v->rule('required',['name', 'phone']);
if($v->validate()) {
    echo "Yay! We're all good!";
} else {
    // Errors
    print_r($v->errors());
}
```

You can also change any of messages on language files and add '{field} to them and test it.

**Comment by jatubio** [comment]
Thank you. Now i can remove my hack from library code :wink:

**Pull request merged**
